### PR TITLE
Enable Travis for Linux, Mac and Windows

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/prebuild/prebuildify/issues/23

Squash at merge.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Hmm interesting. It fails on windows + node 6:

```
C:\Users\travis\build\prebuild\prebuildify\test\package>if not defined npm_config_node_gyp (node "C:\ProgramData\nvs\node\6.16.0\x64\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --target=v6.16.0 --target_arch=x64 --release )  else (node "" rebuild --target=v6.16.0 --target_arch=x64 --release ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB4132: The tools version "2.0" is unrecognized. Available tools versions are "4.0".
```

**Comment by ralphtheninja** [comment]
Possibly related https://github.com/chjj/pty.js/issues/60

**Comment by emilbayes** [comment]
@ralphtheninja Yep check this out: https://github.com/sodium-friends/sodium-native/blob/master/preinstall.js#L62-L92

Was contributed by @enko

**Comment by ralphtheninja** [comment]
Oh ffs

```
$ if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then npm i --global --production windows-build-tools; fi
> windows-build-tools@5.1.0 postinstall C:\ProgramData\nvs\node\6.16.0\x64\node_modules\windows-build-tools
> node ./dist/index.js
C:\ProgramData\nvs\node\6.16.0\x64\node_modules\windows-build-tools\dist\aquire-installers.js:15
async function aquireInstallers(cb) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\ProgramData\nvs\node\6.16.0\x64\node_modules\windows-build-tools\dist\start.js:4:29)
```

**Comment by vweevers** [comment]
FWIW a `--msvs_version` flag would have been enough I think to fix node 6. The `npm install -g windows-build-tools` is becoming the preferred answer for many windows build problems but it's a bit of a sledgehammer if you already have a build environment.

Anyway, +1 to dropping node 6!

**Review by vweevers — APPROVED** [review]

**Pull request merged**
