### PR TITLE
Added fix for building node 10

### PR DESCRIPTION
**Pull request by mathiask88**
see https://github.com/prebuild/prebuild/pull/223

would be nice to have this workaround here as well

### CODE REVIEW

**Comment by mafintosh** [comment]
Only relevant for 10 yea? Should prob only enable it there

**Comment by mathiask88** [comment]
Yes only relevant for 10 AFAIK, sure I can add a version check for this condition

**Comment by vweevers** [comment]
It looks like the flag has been removed in node 15: https://github.com/nodejs/node/pull/27576. The default value in node was the same as the value we set here with `--build_v8_with_gn=false`, so it should not affect node 10-14.

> I can add a version check for this condition

👍 Better to be safe than sorry, and it'll remind us to remove it in the future.

**Comment by vweevers** [comment]
Closes #10

**Comment by mathiask88** [comment]
I added a version check for 10 and 11 only because I had no issues with other node versions.

**Review by vweevers — APPROVED** [review]

**Comment by vweevers** [comment]
Travis is taking too long, I'm canceling.

**Comment by vweevers** [comment]
4.1.1

**Pull request merged**
